version: '2'
services:
  site:
    image: 619e11a9e49f
    #image: evns/grav
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOCKER_USER_PAGES=true
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=Pa55word
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PERMISSIONS=b
      - ADMIN_FULLNAME=Admin
      - ADMIN_TITLE=SiteAdmin
      - GRAV_ADDITIONS=haywire,cacti,archives,tagcloud,highlight,bibleref,relatedpages,feed,taxonomylist
      - DOMAIN=example.com    # set to your root/apex domain
      - GENERATE_CERTS=false  # set to true to automatically setup trusted ssl with let's encrypt
    volumes:
      - grav-backup:/var/www/grav-admin/
volumes:
  grav-backup:
    external: false
