FROM nginx:1.13.12-alpine

# Desired version of grav
ARG GRAV_VERSION=1.4.2

# Install dependencies
RUN apk --no-cache add shadow sudo wget gnupg vim unzip php7 php7-curl php7-gd php7-fpm php7-zip php7-mbstring php7-xml php7-simplexml php7-ctype php7-json php7-openssl php7-session php7-dom tini libressl acme-client

# Set user to nginx
RUN mkdir -p /var/www && chown nginx:nginx /var/www
USER nginx

# Install grav
WORKDIR /var/www
RUN wget https://github.com/getgrav/grav/releases/download/$GRAV_VERSION/grav-admin-v$GRAV_VERSION.zip && \
    unzip grav-admin-v$GRAV_VERSION.zip && \
    rm grav-admin-v$GRAV_VERSION.zip
RUN cd grav-admin && bin/gpm install -f -y admin

# Return to root user
USER root

RUN apk del wget unzip

# Configure nginx with grav
WORKDIR /var/www/grav-admin
RUN cd webserver-configs && \
    sed -i 's/root \/home\/USER\/www\/html/root \/var\/www\/grav-admin/g' nginx.conf && \
    cp nginx.conf /etc/nginx/conf.d/default.conf

# Set the file permissions
RUN usermod -aG nginx nginx

# Run startup script
ADD resources /
ADD data /provided/
ENTRYPOINT [ "/sbin/tini", "--", "/usr/local/bin/startup-alpine.sh" ]
